name: melodia
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  just_audio: 0.10.5
  audio_service: 0.18.18
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  line_icons: ^2.0.3
  on_audio_query: ^2.9.0
  sqflite: ^2.4.2+1
  path: ^1.9.1
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo.png"

flutter_native_splash:
  color: "#0D0B1A"
  image: assets/Logo.png
  color_dark: "#0D0B1A"
  image_dark: assets/Logo.png
  android_12:
    color: "#0D0B1A"
    image: assets/Logo.png
    icon_background_color: "#0D0B1A"
    color_dark: "#0D0B1A"
    image_dark: assets/Logo.png
    icon_background_color_dark: "#0D0B1A"
  ios: false
  web: false
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/Logo.png
