name: Build & Release
on:
  workflow_dispatch:   # allows running from Actions tab
  push:
    tags:
      - 'v*'
on:
  push:
    tags:
      - 'v*'   # triggers when you push tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Archive build
        run: zip -r build.zip ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build.zip
